// This file will be generated by TypeScript compiler
// For now, we'll create a JavaScript version that imports from .ts files
// In production, you would compile TypeScript first

import { Game } from './game.js';

const canvas = document.getElementById('gameCanvas');

if (!canvas) {
  throw new Error('Canvas element not found');
}

const game = new Game(canvas);
game.start();


